<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="12" passed="8" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-10-18T13:59:35 IST" name="Suite" finished-at="2020-10-18T14:01:09 IST" duration-ms="93619">
    <groups>
    </groups>
    <test started-at="2020-10-18T13:59:35 IST" name="Test" finished-at="2020-10-18T14:01:09 IST" duration-ms="93619">
      <class name="com.saucedemo.interview.mypagestest.LoginTest">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:com.saucedemo.interview.mypagestest.LoginTest@61386958]" started-at="2020-10-18T13:59:35 IST" name="setup" finished-at="2020-10-18T13:59:46 IST" duration-ms="10390" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="loginWithoutUserNameandPassword()[pri:0, instance:com.saucedemo.interview.mypagestest.LoginTest@61386958]" started-at="2020-10-18T13:59:46 IST" name="loginWithoutUserNameandPassword" finished-at="2020-10-18T13:59:46 IST" duration-ms="591" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithoutUserNameandPassword -->
        <test-method signature="loginwithInvalidCredentials()[pri:1, instance:com.saucedemo.interview.mypagestest.LoginTest@61386958]" started-at="2020-10-18T13:59:46 IST" name="loginwithInvalidCredentials" finished-at="2020-10-18T13:59:47 IST" duration-ms="379" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginwithInvalidCredentials -->
        <test-method signature="loginwithValidCredentials()[pri:2, instance:com.saucedemo.interview.mypagestest.LoginTest@61386958]" started-at="2020-10-18T13:59:47 IST" name="loginwithValidCredentials" finished-at="2020-10-18T13:59:52 IST" duration-ms="5246" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginwithValidCredentials -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.saucedemo.interview.mypagestest.LoginTest@61386958]" started-at="2020-10-18T13:59:52 IST" name="teardown" finished-at="2020-10-18T13:59:59 IST" duration-ms="6869" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.saucedemo.interview.mypagestest.LoginTest -->
      <class name="com.saucedemo.interview.mypagestest.ProductPageTestInvalidUser">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:com.saucedemo.interview.mypagestest.ProductPageTestInvalidUser@7671cb68]" started-at="2020-10-18T14:00:28 IST" name="setup" finished-at="2020-10-18T14:00:40 IST" duration-ms="12542" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="clicktheProductwithProbUser()[pri:0, instance:com.saucedemo.interview.mypagestest.ProductPageTestInvalidUser@7671cb68]" started-at="2020-10-18T14:00:40 IST" name="clicktheProductwithProbUser" finished-at="2020-10-18T14:00:46 IST" duration-ms="6073" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clicktheProductwithProbUser -->
        <test-method signature="verifyProductDetailsandAddToCartwithProbUser()[pri:1, instance:com.saucedemo.interview.mypagestest.ProductPageTestInvalidUser@7671cb68]" started-at="2020-10-18T14:00:46 IST" name="verifyProductDetailsandAddToCartwithProbUser" finished-at="2020-10-18T14:00:46 IST" duration-ms="204" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.saucedemo.interview.mypagestest.ProductPageTestInvalidUser.verifyProductDetailsandAddToCartwithProbUser(ProductPageTestInvalidUser.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyProductDetailsandAddToCartwithProbUser -->
        <test-method signature="verifyProductInCartwithProbUser()[pri:2, instance:com.saucedemo.interview.mypagestest.ProductPageTestInvalidUser@7671cb68]" started-at="2020-10-18T14:00:47 IST" name="verifyProductInCartwithProbUser" finished-at="2020-10-18T14:00:50 IST" duration-ms="2864" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.saucedemo.interview.mypagestest.ProductPageTestInvalidUser.verifyProductInCartwithProbUser(ProductPageTestInvalidUser.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyProductInCartwithProbUser -->
        <test-method signature="verifySortOperation()[pri:3, instance:com.saucedemo.interview.mypagestest.ProductPageTestInvalidUser@7671cb68]" started-at="2020-10-18T14:00:50 IST" name="verifySortOperation" finished-at="2020-10-18T14:00:55 IST" duration-ms="4145" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.saucedemo.interview.mypagestest.ProductPageTestInvalidUser.verifySortOperation(ProductPageTestInvalidUser.java:50)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySortOperation -->
        <test-method signature="verifyImageStatus()[pri:4, instance:com.saucedemo.interview.mypagestest.ProductPageTestInvalidUser@7671cb68]" started-at="2020-10-18T14:00:55 IST" name="verifyImageStatus" finished-at="2020-10-18T14:01:07 IST" duration-ms="11621" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.saucedemo.interview.mypagestest.ProductPageTestInvalidUser.verifyImageStatus(ProductPageTestInvalidUser.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyImageStatus -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.saucedemo.interview.mypagestest.ProductPageTestInvalidUser@7671cb68]" started-at="2020-10-18T14:01:07 IST" name="teardown" finished-at="2020-10-18T14:01:09 IST" duration-ms="1778" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.saucedemo.interview.mypagestest.ProductPageTestInvalidUser -->
      <class name="com.saucedemo.interview.mypagestest.ProductPageTestValidUser">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:com.saucedemo.interview.mypagestest.ProductPageTestValidUser@73ee04c8]" started-at="2020-10-18T13:59:59 IST" name="setup" finished-at="2020-10-18T14:00:10 IST" duration-ms="10661" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="clicktheProduct()[pri:0, instance:com.saucedemo.interview.mypagestest.ProductPageTestValidUser@73ee04c8]" started-at="2020-10-18T14:00:10 IST" name="clicktheProduct" finished-at="2020-10-18T14:00:18 IST" duration-ms="8326" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clicktheProduct -->
        <test-method signature="verifyProductDetailsandAddToCart()[pri:1, instance:com.saucedemo.interview.mypagestest.ProductPageTestValidUser@73ee04c8]" started-at="2020-10-18T14:00:18 IST" name="verifyProductDetailsandAddToCart" finished-at="2020-10-18T14:00:18 IST" duration-ms="149" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyProductDetailsandAddToCart -->
        <test-method signature="verifyProductInCart()[pri:2, instance:com.saucedemo.interview.mypagestest.ProductPageTestValidUser@73ee04c8]" started-at="2020-10-18T14:00:18 IST" name="verifyProductInCart" finished-at="2020-10-18T14:00:20 IST" duration-ms="2146" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyProductInCart -->
        <test-method signature="verifySortOperation()[pri:3, instance:com.saucedemo.interview.mypagestest.ProductPageTestValidUser@73ee04c8]" started-at="2020-10-18T14:00:20 IST" name="verifySortOperation" finished-at="2020-10-18T14:00:24 IST" duration-ms="4107" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySortOperation -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.saucedemo.interview.mypagestest.ProductPageTestValidUser@73ee04c8]" started-at="2020-10-18T14:00:24 IST" name="teardown" finished-at="2020-10-18T14:00:28 IST" duration-ms="3159" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.saucedemo.interview.mypagestest.ProductPageTestValidUser -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
